---
- name: Run non-interactive script on all hosts
  hosts: all
  become: yes
  vars:
    script_name: config_batman.sh
    mesh_ip_prefix: "192.168.3"
    base_ip_start: 241

  tasks:
    - name: Install batman
      ansible.builtin.apt:
        name: batctl
        state: present

    - name: copy script
      copy:
        src: "{{ script_name}}"
        dest: "/tmp/{{ script_name }}"
        mode: "0755"

    - name: Execute script with mesh IP argument
      ansible.builtin.shell: >
        nohup
        /tmp/{{ script_name }}
        {{ mesh_ip_prefix }}.{{ base_ip_start + groups['all'].index(inventory_hostname) }}
      async: 10
      poll: 0
      ignore_unreachable: true
      register: script_output

    - name: Wait for connection
      ansible.builtin.wait_for_connection:
        delay: 5
        timeout: 60

    - name: Show output
      debug:
        var: script_output.stdout

- name: Run bridge script on manager
  hosts: manager
  become: yes
  vars:
    script_name: bridge.sh

  tasks:
    - name: copy script
      copy:
        src: "{{ script_name}}"
        dest: "/tmp/{{ script_name }}"
        mode: "0755"

    - name: Execute script
      ansible.builtin.shell: "nohup /tmp/{{ script_name }} > /var/log/bridge_setup.log 2>&1"
      async: 10
      poll: 0
      ignore_unreachable: true
      register: log_output

    - name: Wait for connection
      ansible.builtin.wait_for_connection:
        delay: 5
        timeout: 60

    - name: Read log file contents # Write to log because connection is lost during ip flush in bridge script
      ansible.builtin.command: "cat /var/log/bridge_setup.log"
      register: log_output

    - name: Show script output
      debug:
        var: log_output.stdout
# Validage network config BEFORE saving to prevent being locked out
# Use handler to restart network interface

# ADD DEFAULT ROUTE TO BRIDGE SCRIPT
