---
# Expects: mesh_ip, gateway_ip.

- name: Install dependencies
  ansible.builtin.apt:
    name:
      - batctl
      - wireless-tools
      - systemd-resolved
    state: present

- name: Load batman-adv kernel module
  ansible.builtin.command: modprobe batman-adv
  changed_when: false

- name: Stop wpa_supplicant
  ansible.builtin.systemd:
    name: wpa_supplicant
    enabled: false
    state: stopped

- name: Unblock wifi (rfkill)
  ansible.builtin.command: rfkill unblock wifi

- name: Unblock wifi (nmcli radio)
  ansible.builtin.command: nmcli radio wifi on #ensures the system doesn't brick itself if someone re-enables NM
  failed_when: false

- name: Banish NetworkManager to the shadow realm
  ansible.builtin.systemd:
    name: NetworkManager
    enabled: false
    state: stopped

- name: Deploy config_batman2_electric_boogaloo.sh
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../shellscripts/config_batman2_electric_boogaloo.sh"
    dest: /usr/local/bin/config_batman.sh
    mode: "0755"

- name: Deploy batman systemd service
  ansible.builtin.copy:
    dest: /etc/systemd/system/batman.service
    mode: "0644"
    content: |
      [Unit]
      Description=Config and start batman
      After=network.target
      After=systemd-user-sessions.service

      [Service]
      Type=oneshot
      ExecStart=/usr/local/bin/config_batman.sh

      [Install]
      WantedBy=multi-user.target

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable and start batman service
  ansible.builtin.systemd:
    name: batman
    enabled: true
    state: started

- name: Enable networkd
  ansible.builtin.systemd:
    name: systemd-networkd
    enabled: true
    state: started

- name: Deploy netplan config
  ansible.builtin.template:
    src: "{{ playbook_dir }}/templates/90-netplan-workers.yml.j2"
    dest: "/etc/netplan/90-netplan-batman.yaml"
    mode: "0600"

- name: Apply netplan config
  ansible.builtin.command: sudo netplan apply
  
