---
- name: Deploy netplan config
  ansible.builtin.template:
    src: "{{ playbook_dir }}/templates/90-netplan-workers.yml.j2"
    dest: /etc/netplan/90-netplan-workers.yaml
    owner: root
    group: root
    mode: "0600"

- name: Apply that shiii
  ansible.builtin.command: netplan apply

