---
# Expects: mesh_ip, gateway_ip.

- name: Install dependencies
  ansible.builtin.apt:
    name:
      - batctl
      - wireless-tools
      - systemd-resolved
    state: present

- name: Load batman-adv kernel module
  ansible.builtin.command: modprobe batman-adv
  changed_when: false

- name: Prevent NetworkManager from managing wlan0 and bat0
  ansible.builtin.copy:
    dest: /etc/NetworkManager/conf.d/unmanaged-bat0.conf
    mode: "0644"
    content: |
      [keyfile]
      unmanaged-devices=interface-name:bat0;interface-name:wlan0

# - name: Reload NetworkManager config
#   ansible.builtin.command: nmcli general reload conf
#   changed_when: false

- name: Deploy config_batman.sh
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../shellscripts/config_batman.sh"
    dest: /usr/local/bin/config_batman.sh
    mode: "0755"

- name: Deploy batman systemd service
  ansible.builtin.copy:
    dest: /etc/systemd/system/batman.service
    mode: "0644"
    content: |
      [Unit]
      Description=Config and start batman
      After=network.target
      After=systemd-user-sessions.service

      [Service]
      Type=oneshot
      ExecStart=/usr/local/bin/config_batman.sh {{ mesh_ip }} {{ gateway_ip }}

      [Install]
      WantedBy=multi-user.target

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable and start batman service
  ansible.builtin.systemd:
    name: batman
    enabled: true
    state: started

- name: Wait for connection to recover after wlan0 reconfiguration
  ansible.builtin.wait_for_connection:
    delay: 5
    timeout: 60
- name: Enable networkd
  ansible.builtin.systemd:
    name: systemd-networkd
    enabled: true
    state: started
