apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensehat-collector
  labels:
    app: sensehat-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensehat-collector
  template:
    metadata:
      labels:
        app: sensehat-collector
    spec:
      schedulerName: custom-scheduler
      nodeSelector:
        sensehat: "true"
      containers:
        - name: collector
          image: sondrejk/sensehat-collector:latest
          imagePullPolicy: Always
          securityContext:
            privileged: true
          env:
            - name: MQTT_BROKER
              value: "mosquitto.default.svc.cluster.local"
            - name: NetworkComRequirements
              value: '[{"Target": "mosquitto", "Latency": 50, "Throughput": 0.1}]'
          resources:
            requests:
              cpu: "200m"
              memory: "64Mi"
          volumeMounts:
            - name: data
              mountPath: /data
            - name: dev
              mountPath: /dev
      volumes:
        - name: data
          hostPath:
            path: /home/pi/sensehat-data
            type: DirectoryOrCreate
        - name: dev
          hostPath:
            path: /dev
