---
# Usage: ansible-playbook -i inventories/static.ini provision_single_manager.yml \
#          -e "new_host_ip=192.168.3.X pi_hostname=manager0"
- name: Add new manager to runtime inventory
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Abort if host already in inventory
      ansible.builtin.meta: end_play
      when: new_host_ip in groups['all']

    - name: Add host to runtime inventory
      ansible.builtin.add_host:
        name: "{{ pi_hostname }}"
        ansible_host: "{{ new_host_ip }}"
        ansible_user: pi
        ansible_password: raspberry
        groups: new_managers

- name: Set hostname on new manager
  hosts: new_managers
  become: true

  tasks:
    - name: Disable cloud-init
      ansible.builtin.include_tasks: tasks/disable_cloud_init.yml

    - name: Set hostname
      ansible.builtin.include_tasks: tasks/set_hostname.yml

- name: Provision batman mesh on new manager
  hosts: new_managers
  become: true
  vars:
    # Manager is always the batman gateway at .1
    mesh_ip_prefix: "192.168.42"

  tasks:
    - name: Provision batman on node
      ansible.builtin.include_tasks: tasks/provision_batman_node.yml
      vars:
        mesh_ip: "{{ mesh_ip_prefix }}.1"
        gateway_ip: "{{ mesh_ip_prefix }}.1"

- name: Configure NAT routing on new manager
  hosts: new_managers
  become: true
  vars:
    wan_interface: eth0
    bat_interface: bat0

  tasks:
    - name: Configure NAT
      ansible.builtin.include_tasks: tasks/configure_nat.yml

- name: Install k3s server on new manager
  hosts: new_managers
  become: true

  tasks:
    - name: Install k3s server
      ansible.builtin.include_tasks: tasks/install_k3s_manager.yml

- name: Fetch k3s config to controller
  hosts: new_managers
  tasks:
    - name: Copy k3s config
      become: true
      ansible.builtin.fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "{{ playbook_dir }}/kubeconfig.yml"
        flat: yes

- name: Set up logs directory
  hosts: new_managers
  become: true

  tasks:
    - name: Set up logs
      ansible.builtin.include_tasks: tasks/setup_logs.yml

- name: Persist new manager to inventory
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Add manager to dynamic inventory
      ansible.builtin.lineinfile:
        path: "{{ playbook_dir }}/inventories/dynamic.ini"
        insertafter: '^\[manager\]'
        line: "{{ pi_hostname }} ansible_host={{ new_host_ip }} ansible_user=pi ansible_password=raspberry"
